# Funding Configuration
# This file configures funding options for the UCID project.
# Reference: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [ucid-foundation]

# Open Collective
open_collective: ucid

# Custom funding URLs
custom:
  - https://ucid.org/donate
